version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terte_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test
