version: '3.9'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terte_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test
    networks:
      - mynetwork

  test-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - ./src/test/resources/sql:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
    driver: bridge
