version: '3.9'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terte_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test
  test-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    container_name: test-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
