spring:
  datasource:
    url: jdbc:mysql://localhost:3306/terte_db
    username: test_user
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always
