name: Run Tests on Push

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose
        run: docker compose version

      - name: Set up Docker Compose
        run: docker compose -f application/docker-compose.yml up -d test-db

      - name: Run Spring Boot application (For JPA creating tables)
        run: ./gradlew bootRun &

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3307 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Insert test data into MySQL
        run: |
          docker exec test-db sh -c 'exec mysql -u testuser -ptestpassword testdb < /data/test-data.sql'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3307/testdb
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpassword
        run: ./gradlew :application:test

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f application/docker-compose.yml down
