name: Run Tests on Push

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose
        run: docker compose version

      - name: Set up Docker Compose
        run: docker compose -f application/docker-compose.yml up -d test-db

      - name: Check running containers
        run: docker ps -a

      - name: Check MySQL container logs
        run: docker logs test-db || true

      - name: Wait for MySQL to be fully ready
        run: |
          echo "Waiting for MySQL to be fully ready..."
          for i in {1..60}; do
            if docker exec test-db mysql -u testuser -ptestpassword -e "SELECT 1" testdb > /dev/null 2>&1; then
              echo "MySQL is fully ready!"
              break
            fi
            echo "Waiting for MySQL to be fully available..."
            sleep 2
          done
          if ! docker exec test-db mysql -u testuser -ptestpassword -e "SELECT 1" testdb > /dev/null 2>&1; then
            echo "MySQL failed to become ready in time."
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Spring Boot to create tables
        run: |
          nohup ./gradlew :application:bootRun > application.log 2>&1 &
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep UP; then
              echo "Spring Boot is ready, and tables are created!"
              break
            fi
            echo "Waiting for Spring Boot to initialize..."
            sleep 5
          done
          if ! curl -s http://localhost:8080/actuator/health | grep UP; then
            echo "Spring Boot failed to start."
            cat application.log
            exit 1
          fi

      - name: Print application logs on failure
        if: failure()
        run: cat application.log

      - name: Insert test data into MySQL
        run: |
          docker exec test-db sh -c 'exec mysql -u testuser -ptestpassword testdb < /docker-entrypoint-initdb.d/test-data.sql'

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://test-db:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpassword
        run: ./gradlew :application:test

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f application/docker-compose.yml down
